### ISSUE TITLE
발표자: 김도균

### ISSUE THREAD

**Issue by justinyoo** [krazure/ga2021kr#17]
![김도균](https://raw.githubusercontent.com/krazure/ga2021kr/main/media/speakers/kimdokyun.jpg)

**애저 트레이너**

독립 Azure 트레이너. Korea Azure User Group 운영자와 친한 마이크로소프트 MVP.  "한국 최초의 Azure 저서 출간"이라는 타이틀 획득!

**Comment by steelflea** [comment]
> ![김도균](https://raw.githubusercontent.com/krazure/ga2021kr/main/media/speakers/kimdokyun.jpg)
> 
> **애저 트레이너**
> 
> 독립 Azure 트레이너. 마이크로소프트 MVP. "한국 최초의 Azure 저서 출간"이라는 타이틀 획득!

**Comment by steelflea** [comment]
> ![kimdokyun](https://user-images.githubusercontent.com/36403352/115186063-fdd95600-a11b-11eb-9e27-fab6bfd2ce5a.jpg)

> **애저 트레이너**
> 
> 남은 인생, 잘 놀고 잘 먹기 위해 기술 책쓰고 마이크로소프트 기술(요즘은 특히 Azure)을 강의합니다.
