### ISSUE TITLE
Azure Cloud Shell로 도전하는 개발 생산성 만렙: 남정현

### ISSUE THREAD

**Issue by justinyoo** [krazure/ga2021kr#27]
* URL: [https://bit.ly/ga2021kr-azdevs](https://bit.ly/ga2021kr-azdevs)
* 시각: 4월 17일, 오후 4시 20분
* 발표자: [남정현](/krazure/ga2021kr/issues/22)
제목: Azure Cloud Shell로 도전하는 개발 생산성 만렙
내용: Azure의 보조 기능으로 Azure 포털에서 처음 제공되었던 Azure Cloud Shell은 이제 Azure의 중요한 기능 중 하나로 자리잡았는데요, Azure Cloud Shell을 다양하게 활용할 수 있는 방법을 살펴보고, 어떻게 이용하면 편리하게 작업할 수 있는지 짧고 알차게 전달해드리겠습니다.

**Comment by rkttu** [comment]
내용 변경 요청드립니다.

- 제목: Azure Cloud Shell로 도전하는 개발 생산성 만렙

- 세션 설명: Azure의 보조 기능으로 Azure 포털에서 처음 제공되었던 Azure Cloud Shell은 이제 Azure의 중요한 기능 중 하나로 자리잡았는데요, Azure Cloud Shell을 다양하게 활용할 수 있는 방법을 살펴보고, 어떻게 이용하면 편리하게 작업할 수 있는지 짧고 알차게 전달해드리겠습니다.

- 변경 사유: Azure Cloud Service의 실제 배포와 테스트 과정에서 매우 많은 기술적인 어려움이 발생하였으며, Github Action 역시 기술적인 문제가 발생하여 데모 동영상 레코딩을 진행할 수 없어 긴급하게 변경을 진행합니다.
