### ISSUE TITLE
Azure PaaS 기반 ML 플랫폼 구성 방법론: 배준현

### ISSUE THREAD

**Issue by justinyoo** [krazure/ga2021kr#36]
- URL: https://bit.ly/ga2021kr-azops
- 시각: 4월 17일, 오후 4시 20분
- 발표자: [배준현](https://github.com/krazure/ga2021kr/issues/35)
- 내용:

**Comment by SystemOutCoding** [comment]
내용 : 
1. Team Data Science Process(TDSP) 데이터 과학 방법론을 Azure PaaS 와 SaaS 서비스 기반으로 구성하는 예제를 다룹니다.
2. '데이터 과학 수명주기'에 대한 예제 도메인 정의를 기반으로 '표준화된 프로젝트 구조'를 Azure DevOps 기반으로 구성 및 운영 하는 방법론을 소개 합니다.
